Update SORACOM-LPWAN-with-features.csv
soracom/coverage-tests pull request #2
Opened 2024-07-24 16:08 UTC by MarPiSora

July 2024 update

2024-07-29 07:01 UTC, MarPiSora reviewed
looks good now

2024-07-29 07:04 UTC, MarPiSora commented
hello @fstubner - may I ask for a quick review?
No major changes...just some new networks and aupdated timestamps to show.

2024-07-29 13:51 UTC, zelkovab commented on SORACOM-LPWAN-with-features.csv
> +Japan,JPN,44051,KDDI,LTE-M,B18,plan01s,Validated,PSM | SMS,07/01/2024
Could you remove plan01s KDDI (44051) from the list?
We know the network attach itself works but we need to hide it from the political reasons..

2024-07-29 13:52 UTC, zelkovab requested changes
added one comment for KDDI(44051) x 01s. the rest looks good to me.

2024-07-29 13:55 UTC, MarPiSora commented
removed KDDI plan01s LTE-M
-> adapted this is test sheet as well to be not shown anymore in the future

2024-07-30 08:42 UTC, zelkovab approved these changes
LGTM. Thanks!

2024-07-30 08:47 UTC, merged